USE EXERCISE_DB.PUBLIC

CREATE OR REPLACE STAGE EXERCISE_DB.EXTERNAL_STAGES.UNSTRUCTURED
    url = 's3://snowflake-assignments-mc/unstructureddata'
LIST @EXERCISE_DB.EXTERNAL_STAGES.UNSTRUCTURED
    
CREATE OR REPLACE file format EXERCISE_DB.FILE_FORMATS.JSONFORMAT
TYPE = JSON

DESC file format EXERCISE_DB.FILE_FORMATS.JSONFORMAT

CREATE OR REPLACE TABLE EXERCISE_DB.PUBLIC.JSON_RAW(
    Raw variant
)

COPY INTO EXERCISE_DB.PUBLIC.JSON_RAW
FROM @EXERCISE_DB.EXTERNAL_STAGES.UNSTRUCTURED
file_format = EXERCISE_DB.FILE_FORMATS.JSONFORMAT
pattern = '.*.json.*'

SELECT * FROM JSON_RAW