CREATE OR REPLACE TABLE EMPLOYEES(
    customer_id int,
    first_name varchar(50),
    last_name varchar(50),
    email varchar(50),
    age int,
    department varchar(50)
)

CREATE OR REPLACE STAGE EXERCISE_DB.EXTERNAL_STAGES.AWS_EXAMPLE2
url = 's3://snowflake-assignments-mc/copyoptions/example2'

LIST @EXERCISE_DB.EXTERNAL_STAGES.AWS_EXAMPLE2

CREATE file format EXERCISE_DB.FILE_FORMATS.EXAMPLE2
TYPE = 'csv'
FIELD_DELIMITER = ','
SKIP_HEADER = 1;

COPY INTO EMPLOYEES
FROM @EXERCISE_DB.EXTERNAL_STAGES.AWS_EXAMPLE2
file_format = (FORMAT_NAME=EXERCISE_DB.FILE_FORMATS.EXAMPLE2)
pattern = '.*employee.*'
ON_ERROR = 'CONTINUE'

CREATE TABLE REJECTED AS (
    SELECT REJECTED_RECORD FROM (
    SELECT * FROM TABLE (VALIDATE(EMPLOYEES,JOB_ID =>'01b38817-0305-112b-0004-ea7f000402a2'))
    )
)

SELECT * FROM REJECTED