USE MANAGED_DB.EXTERNAL_STAGES

CREATE file format MANAGED_DB.FILE_FORMATS.PARQUET_FORMAT
TYPE = 'PARQUET'

CREATE STAGE MANAGED_DB.EXTERNAL_STAGES.AWS_PARQUET
    url = 's3://snowflakeparquetdemo'
    file_format = MANAGED_DB.FILE_FORMATS.PARQUET_FORMAT

LIST @AWS_PARQUET

//Viewing the file and viewing the contents
SELECT * FROM @MANAGED_DB.EXTERNAL_STAGES.AWS_PARQUET

//Copying the PARQUET file into a table
//First step is we use the SELECT statement on the parquet stage
CREATE OR REPLACE TABLE MANAGED_DB.PUBLIC.PARTQUET_TABLE AS (SELECT
$1:__index_level_0__::INT as Index_Level,
$1:id::STRING as ID,
$1:cat_id::STRING as CAT_ID,
$1:d::INT as D,
DATE($1:date::INT) as Date,
$1:dept_id::STRING AS DEPT_ID,
$1:item_id::STRING AS ITEM_ID,
$1:state_id::STRING AS STATE_ID,
$1:store_id::STRING AS STORE_ID,
$1:value::INT AS VALUE,
METADATA$FILENAME AS FILE_NAME,
METADATA$FILE_ROW_NUMBER AS ROWNUMBER,
TO_TIMESTAMP_NTZ(current_timestamp) AS LOAD_DATE
FROM @MANAGED_DB.EXTERNAL_STAGES.AWS_PARQUET);

SELECT * FROM MANAGED_DB.PUBLIC.PARTQUET_TABLE

SELECT MAX(D) FROM MANAGED_DB.PUBLIC.PARTQUET_TABLE